name: frost

services:

  psb:
    container_name: psb
    build:
      dockerfile: Dockerfile.psb
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  frost:
    container_name: frost
    build:
      dockerfile: Dockerfile.frost
    environment:
      - HTTPSERVERPORT=8080
      - FEATURES=frost0,badevann,glider,verticalprofile
    ports:
      - 8080:8080
