# Stage 1: Build
FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /app/frost main/main.go

# Stage 2: Final
FROM alpine:latest
RUN mkdir /frost
COPY --from=builder /app/frost /frost
COPY --from=builder /app/templates /frost/templates
COPY --from=builder /app/static /frost/static
WORKDIR /frost
CMD ["./frost"]
