name: frost

services:

  # psb:
  #   build:
  #     dockerfile: Dockerfile.psb

  frost:
    build:
      dockerfile: Dockerfile.frost
    environment:
      - HTTPSERVERPORT=8080
      - FEATURES=frost0,badevann,glider,verticalprofile
    ports:
      - 8080:8080
