name: frost

services:

  psb:
    container_name: psb
    build:
      dockerfile: Dockerfile.psb
    ports:
      - 5433:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d datasets']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  frost:
    container_name: frost
    build:
      dockerfile: Dockerfile.frost
    ports:
      - 8080:8080
    depends_on:
      psb:
        condition: service_healthy
        restart: true
    environment:
      - HTTPSERVERPORT=8080
      - FEATURES=frost0,sst,glider,verticalprofile
      - OBSBACKEND=postgres
      - PSBHOST=psb
      - PSBPORT=5432
      - PSBPASSWORD=mysecretpassword
